# Numpy

In [5]:
import numpy as np

In [7]:
my_list= [1,2,3]
np.array (my_list)

array([1, 2, 3])

### Add two arrays

In [10]:
arr1=np.array([3,5,6,8,3,8])
arr2=np.array([3,8,2,5,9,5])
print(arr1+arr2)

[ 6 13  8 13 12 13]


### Element-wise scalar addition

In [14]:
print(arr1+10)

[13 15 16 18 13 18]


### To get the dimension of array

In [17]:
arr1.ndim # Dimension

1

In [19]:
import numpy as np

# 1-dimensional array
arr1 = np.array([1, 2, 3])
print(arr1.ndim)  # Output: 1

# 2-dimensional array
arr2 = np.array([[1, 2], [3, 4]])
print(arr2.ndim)  # Output: 2

# 3-dimensional array
arr3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr3.ndim)  # Output: 3

1
2
3


### 'shape' returns a tuple with each index having the number of corresponding elements.

In [22]:
import numpy as np
my_List1= [1,2,3,4,5,6]
arr1= np.array(my_List1)
arr1.shape 

(6,)

In [24]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape) # Here shape returns (2, 4), which means that the array has 2 dimensions, where the first dimension has 2 elements and the second has 4.

(2, 4)


### Data type

In [27]:
arr1.dtype #Data type

dtype('int32')

In [29]:
arr3=np.array([1,3,5,7,'a']) # Different data types in an array
arr3

array(['1', '3', '5', '7', 'a'], dtype='<U11')

### Syntax: numpy.size(arr, axis=None)
#### axis: [int, optional] Axis(x,y,z) along which the elements(rows or columns) are counted. 
#### By default, it gives the total number of elements in a array. Here it is 3*3=9
#### Returns: [int] Return the number of elements along a given axis. 
 

In [32]:
arr4= np.array([[1,2,3],[4,6,7],[2,8,9]])
print(arr4.ndim) # Dimension
print(arr4.shape) # Number of rows or column
print(arr4.dtype) #Data type
print(arr4.size)

2
(3, 3)
int32
9


In [34]:
arr5= np.array([[1,2],[3,4]])
print(arr5.ndim) # Dimension
print(arr5.shape) 

2
(2, 2)


### List Vs Array
#### List: Heterogeneous, dynamic (sizec can change during run time)
#### Array: Homogeneous (Elements are of same data type), fixed (size defined at creation)- hence faster for numerical operations

In [25]:
print(list(range(5,10)))

[5, 6, 7, 8, 9]


## Print values within a range

In [37]:
np.arange(10,100)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

In [33]:
arr5=np.arange(10,100,10)
arr5

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [39]:
print(np.arange(100,0,-10))

[100  90  80  70  60  50  40  30  20  10]


### Reshape the array without changing the number of elements


In [46]:
arr6=np.array([1,2,3,4,5,6]) #array7 is a 1-dimensional array with 6 elements.
print(arr6)
arr6.reshape(2,3) #Reshapes array7 into 2 rows and 3 columns. (Row*Column should be equal to number of elements of array7)

[1 2 3 4 5 6]


array([[1, 2, 3],
       [4, 5, 6]])

In [50]:
arr7=np.arange(1,101)
print(arr7)
arr7.reshape(10,10)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [52]:
arr7.reshape(2,50)
arr7.reshape(50,2)

array([[  1,   2],
       [  3,   4],
       [  5,   6],
       [  7,   8],
       [  9,  10],
       [ 11,  12],
       [ 13,  14],
       [ 15,  16],
       [ 17,  18],
       [ 19,  20],
       [ 21,  22],
       [ 23,  24],
       [ 25,  26],
       [ 27,  28],
       [ 29,  30],
       [ 31,  32],
       [ 33,  34],
       [ 35,  36],
       [ 37,  38],
       [ 39,  40],
       [ 41,  42],
       [ 43,  44],
       [ 45,  46],
       [ 47,  48],
       [ 49,  50],
       [ 51,  52],
       [ 53,  54],
       [ 55,  56],
       [ 57,  58],
       [ 59,  60],
       [ 61,  62],
       [ 63,  64],
       [ 65,  66],
       [ 67,  68],
       [ 69,  70],
       [ 71,  72],
       [ 73,  74],
       [ 75,  76],
       [ 77,  78],
       [ 79,  80],
       [ 81,  82],
       [ 83,  84],
       [ 85,  86],
       [ 87,  88],
       [ 89,  90],
       [ 91,  92],
       [ 93,  94],
       [ 95,  96],
       [ 97,  98],
       [ 99, 100]])

### Calculating time required for operation in Python and Numpy

In [55]:
L=range(1000)
%timeit nums=[i**2 for i in L]

123 μs ± 1.76 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [56]:
nums=np.arange(1000)
%timeit nums**2

2.52 μs ± 347 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


## Creating matrices

In [60]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [62]:
np.eye(3)# identity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [64]:
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [66]:
np.sum([1,2,3,4])

10

In [68]:
x=np.array(range(1,100))
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [70]:
np.mean(x)

50.0

In [72]:
np.std(x)

28.577380332470412

In [74]:
std=np.sqrt(np.sum((x-np.mean(x))**2)/x.size)
std

28.577380332470412

In [76]:
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [78]:
z=np.diag([1,2,3,4])
z

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [80]:
d=np.random.random(3)
d

array([0.33530004, 0.68387082, 0.97039202])

In [82]:
np.random.randn(4)

array([ 0.5252154 , -0.59328226, -0.59729362,  0.68748871])

In [84]:
np.random.randint(0,20,3)

array([16,  6,  5])

In [86]:
a=np.arange(10)
a.dtype

dtype('int32')

In [88]:
a=np.arange(10,dtype=np.float32)
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

In [90]:
np.array([1+3j]).dtype

dtype('complex128')

In [92]:
np.array(["ram","hello"])

array(['ram', 'hello'], dtype='<U5')

In [94]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [96]:
a[3]=10
a

array([ 0,  1,  2, 10,  4,  5,  6,  7,  8,  9])

In [98]:
b=a[: : 2]
b     #indexing

array([0, 2, 4, 6, 8])

In [100]:
a[::-2]

array([ 9,  7,  5, 10,  1])

In [102]:
a[1::2][::-1]

array([ 9,  7,  5, 10,  1])

In [104]:
a[1::2][::-1][::-1]

array([ 1, 10,  5,  7,  9])

In [106]:
np.shares_memory(a,b)

True

In [108]:
c=a[::2].copy()
c

array([0, 2, 4, 6, 8])

In [110]:
a=np.zeros((4,4))
b=np.ones((4,4))
a,b

(array([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]),
 array([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]))

In [112]:
c=np.vstack((a,b))
c.shape
a,b
c

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [114]:
d=np.hstack((a,b))
d.shape
d

array([[0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.]])

In [116]:
np.concatenate([a,b],axis=1)

array([[0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.]])

In [118]:
array1=np.array([1,2,3])
array1.T.shape

(3,)

In [120]:
a=np.arange(4)
b=a.T
np.dot(a,b)

14

# Pandas

In [124]:
import pandas as pd

In [126]:
weather_data=[("1/1/2024",32,6,"rain"),("2/2/2024",35,7,"sunny")]

In [128]:
df=pd.DataFrame(weather_data,\
                columns=["date","temperature","wind","climate"])

In [130]:
df

date  temperature  wind climate
0  1/1/2024           32     6    rain
1  2/2/2024           35     7   sunny

In [142]:
df= pd.read_csv("D:\\ICT_DataScience\\Excel worksheet\\auto-mpg.csv")
df

mpg  cylinders  displacement horsepower  weight  acceleration  \
0    18.0          8         307.0        130    3504          12.0   
1    15.0          8         350.0        165    3693          11.5   
2    18.0          8         318.0        150    3436          11.0   
3    16.0          8         304.0        150    3433          12.0   
4    17.0          8         302.0        140    3449          10.5   
..    ...        ...           ...        ...     ...           ...   
393  27.0          4         140.0         86    2790          15.6   
394  44.0          4          97.0         52    2130          24.6   
395  32.0          4         135.0         84    2295          11.6   
396  28.0          4         120.0         79    2625          18.6   
397  31.0          4         119.0         82    2720          19.4   

     model year  origin                   car name  
0            70       1  chevrolet chevelle malibu  
1            70       1          buick skylark 320  
2            70       1         plymouth satellite  
3            70       1              amc rebel sst  
4            70       1                ford torino  
..          ...     ...                        ...  
393          82       1            ford mustang gl  
394          82       2                  vw pickup  
395          82       1              dodge rampage  
396          82       1                ford ranger  
397          82       1                 chevy s-10  

[398 rows x 9 columns]

In [144]:
df.shape

(398, 9)

In [146]:
df.head(2)

mpg  cylinders  displacement horsepower  weight  acceleration  model year  \
0  18.0          8         307.0        130    3504          12.0          70   
1  15.0          8         350.0        165    3693          11.5          70   

   origin                   car name  
0       1  chevrolet chevelle malibu  
1       1          buick skylark 320

In [148]:
df["mpg"]# print one column

0      18.0
1      15.0
2      18.0
3      16.0
4      17.0
       ... 
393    27.0
394    44.0
395    32.0
396    28.0
397    31.0
Name: mpg, Length: 398, dtype: float64

In [150]:
df.mpg

0      18.0
1      15.0
2      18.0
3      16.0
4      17.0
       ... 
393    27.0
394    44.0
395    32.0
396    28.0
397    31.0
Name: mpg, Length: 398, dtype: float64

In [152]:
df.columns

Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'model year', 'origin', 'car name'],
      dtype='object')

In [154]:
df.columns.tolist()

['mpg',
 'cylinders',
 'displacement',
 'horsepower',
 'weight',
 'acceleration',
 'model year',
 'origin',
 'car name']

In [156]:
df[["mpg","cylinders","displacement"]]

mpg  cylinders  displacement
0    18.0          8         307.0
1    15.0          8         350.0
2    18.0          8         318.0
3    16.0          8         304.0
4    17.0          8         302.0
..    ...        ...           ...
393  27.0          4         140.0
394  44.0          4          97.0
395  32.0          4         135.0
396  28.0          4         120.0
397  31.0          4         119.0

[398 rows x 3 columns]

In [158]:
new_df=df[["car name","weight"]]

In [160]:
new_df.to_excel("output.xlsx",sheet_name="sheet1")

In [161]:
df.describe()

mpg   cylinders  displacement       weight  acceleration  \
count  398.000000  398.000000    398.000000   398.000000    398.000000   
mean    23.514573    5.454774    193.425879  2970.424623     15.568090   
std      7.815984    1.701004    104.269838   846.841774      2.757689   
min      9.000000    3.000000     68.000000  1613.000000      8.000000   
25%     17.500000    4.000000    104.250000  2223.750000     13.825000   
50%     23.000000    4.000000    148.500000  2803.500000     15.500000   
75%     29.000000    8.000000    262.000000  3608.000000     17.175000   
max     46.600000    8.000000    455.000000  5140.000000     24.800000   

       model year      origin  
count  398.000000  398.000000  
mean    76.010050    1.572864  
std      3.697627    0.802055  
min     70.000000    1.000000  
25%     73.000000    1.000000  
50%     76.000000    1.000000  
75%     79.000000    2.000000  
max     82.000000    3.000000

In [162]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64  
 2   displacement  398 non-null    float64
 3   horsepower    398 non-null    object 
 4   weight        398 non-null    int64  
 5   acceleration  398 non-null    float64
 6   model year    398 non-null    int64  
 7   origin        398 non-null    int64  
 8   car name      398 non-null    object 
dtypes: float64(3), int64(4), object(2)
memory usage: 28.1+ KB


In [166]:
g=df.groupby("model year")
g.max()

mpg  cylinders  displacement horsepower  weight  acceleration  \
model year                                                                   
70          27.0          8         455.0         97    4732          20.5   
71          35.0          8         400.0          ?    5140          20.5   
72          28.0          8         429.0         97    4633          23.5   
73          29.0          8         455.0         95    4997          21.0   
74          32.0          8         350.0          ?    4699          21.0   
75          33.0          8         400.0         98    4668          21.0   
76          33.0          8         351.0         95    4380          22.2   
77          36.0          8         400.0         98    4335          19.0   
78          43.1          8         318.0         97    4080          21.5   
79          37.3          8         360.0         90    4360          24.8   
80          46.6          6         225.0          ?    3381          23.7   
81          39.1          8         350.0          ?    3725          20.7   
82          44.0          6         262.0          ?    3035          24.6   

            origin                      car name  
model year                                        
70               3  volkswagen 1131 deluxe sedan  
71               3          volkswagen model 111  
72               3               volvo 145e (sw)  
73               3                   volvo 144ea  
74               3             volkswagen dasher  
75               3                   volvo 244dl  
76               3                     vw rabbit  
77               3      volkswagen rabbit custom  
78               3                   volvo 264gl  
79               3              vw rabbit custom  
80               3          vw rabbit c (diesel)  
81               3                  volvo diesel  
82               3                     vw pickup

In [168]:
df_sample = df.sample(10)
df_sample

mpg  cylinders  displacement horsepower  weight  acceleration  \
312  37.2          4          86.0         65    2019          16.4   
310  38.1          4          89.0         60    1968          18.8   
34   16.0          6         225.0        105    3439          15.5   
100  18.0          6         250.0         88    3021          16.5   
381  36.0          4         107.0         75    2205          14.5   
333  32.7          6         168.0        132    2910          11.4   
23   26.0          4         121.0        113    2234          12.5   
36   19.0          6         250.0         88    3302          15.5   
38   14.0          8         350.0        165    4209          12.0   
338  27.2          4         135.0         84    2490          15.7   

     model year  origin                   car name  
312          80       3                 datsun 310  
310          80       3      toyota corolla tercel  
34           71       1  plymouth satellite custom  
100          73       1              ford maverick  
381          82       3               honda accord  
333          80       3              datsun 280-zx  
23           70       2                   bmw 2002  
36           71       1            ford torino 500  
38           71       1           chevrolet impala  
338          81       1           plymouth reliant

In [170]:
for x,model_df in g:
    print(x)
    print(model_df)

70
     mpg  cylinders  displacement horsepower  weight  acceleration  \
0   18.0          8         307.0        130    3504          12.0   
1   15.0          8         350.0        165    3693          11.5   
2   18.0          8         318.0        150    3436          11.0   
3   16.0          8         304.0        150    3433          12.0   
4   17.0          8         302.0        140    3449          10.5   
5   15.0          8         429.0        198    4341          10.0   
6   14.0          8         454.0        220    4354           9.0   
7   14.0          8         440.0        215    4312           8.5   
8   14.0          8         455.0        225    4425          10.0   
9   15.0          8         390.0        190    3850           8.5   
10  15.0          8         383.0        170    3563          10.0   
11  14.0          8         340.0        160    3609           8.0   
12  15.0          8         400.0        150    3761           9.5   
13  14.0         

In [172]:
us_weather=pd.DataFrame({
                           "city":["newyork","chitago","seatle"],
                           "temperature":[32,21,35],
                            "humidity":[60,75,78]
                           })

In [174]:
us_weather

city  temperature  humidity
0  newyork           32        60
1  chitago           21        75
2   seatle           35        78

In [176]:
india_weather=pd.DataFrame({
                           "city":["banglore","mumbai","tvm"],
                           "temperature":[30,34,32],
                            "humidity":[20,60,55]
                           })

In [178]:
india_weather

city  temperature  humidity
0  banglore           30        20
1    mumbai           34        60
2       tvm           32        55

In [180]:
weather_us_india=pd.concat([us_weather,india_weather],\
                           ignore_index= True)
weather_us_india

city  temperature  humidity
0   newyork           32        60
1   chitago           21        75
2    seatle           35        78
3  banglore           30        20
4    mumbai           34        60
5       tvm           32        55

In [182]:
weather_us_india["temperature"]<30

0    False
1     True
2    False
3    False
4    False
5    False
Name: temperature, dtype: bool

In [184]:
weather_us_india[weather_us_india["temperature"]<30]
weather_us_india

city  temperature  humidity
0   newyork           32        60
1   chitago           21        75
2    seatle           35        78
3  banglore           30        20
4    mumbai           34        60
5       tvm           32        55

In [186]:
weather_us_india=pd.concat([us_weather,india_weather],\
                           ignore_index= True,axis=1)
weather_us_india

0   1   2         3   4   5
0  newyork  32  60  banglore  30  20
1  chitago  21  75    mumbai  34  60
2   seatle  35  78       tvm  32  55

In [192]:
pd.merge(india_weather,us_weather, on="temperature") #Places that have same temperature

city_x  temperature  humidity_x   city_y  humidity_y
0    tvm           32          55  newyork          60

In [194]:
df=pd.DataFrame([1,2,3,4], index=[48,43,21,45])# Index
df.loc[45]

0    4
Name: 45, dtype: int64

## Series

In [205]:
city1=pd.Series([12,-6,8,-3], index= ["day1","day2","day3","day4"])
city1                                                                #series

day1    12
day2    -6
day3     8
day4    -3
dtype: int64

In [207]:
city1.isna()    #missingvalue

day1    False
day2    False
day3    False
day4    False
dtype: bool

In [209]:
df.isna().sum()

0    0
dtype: int64

In [215]:
df= pd.read_csv("D:\\ICT_DataScience\\Excel worksheet\\auto-mpg.csv")
df["car name"].unique()

array(['chevrolet chevelle malibu', 'buick skylark 320',
       'plymouth satellite', 'amc rebel sst', 'ford torino',
       'ford galaxie 500', 'chevrolet impala', 'plymouth fury iii',
       'pontiac catalina', 'amc ambassador dpl', 'dodge challenger se',
       "plymouth 'cuda 340", 'chevrolet monte carlo',
       'buick estate wagon (sw)', 'toyota corona mark ii',
       'plymouth duster', 'amc hornet', 'ford maverick', 'datsun pl510',
       'volkswagen 1131 deluxe sedan', 'peugeot 504', 'audi 100 ls',
       'saab 99e', 'bmw 2002', 'amc gremlin', 'ford f250', 'chevy c20',
       'dodge d200', 'hi 1200d', 'chevrolet vega 2300', 'toyota corona',
       'ford pinto', 'plymouth satellite custom', 'ford torino 500',
       'amc matador', 'pontiac catalina brougham', 'dodge monaco (sw)',
       'ford country squire (sw)', 'pontiac safari (sw)',
       'amc hornet sportabout (sw)', 'chevrolet vega (sw)',
       'pontiac firebird', 'ford mustang', 'mercury capri 2000',
       'opel 1900'

In [217]:
df["cylinders"].value_counts()  

cylinders
4    204
8    103
6     84
3      4
5      3
Name: count, dtype: int64

In [219]:
df.values#return call numpy

array([[18.0, 8, 307.0, ..., 70, 1, 'chevrolet chevelle malibu'],
       [15.0, 8, 350.0, ..., 70, 1, 'buick skylark 320'],
       [18.0, 8, 318.0, ..., 70, 1, 'plymouth satellite'],
       ...,
       [32.0, 4, 135.0, ..., 82, 1, 'dodge rampage'],
       [28.0, 4, 120.0, ..., 82, 1, 'ford ranger'],
       [31.0, 4, 119.0, ..., 82, 1, 'chevy s-10']], dtype=object)

In [221]:
#drop the column
car_new=df.drop(["origin","car name"],axis=1)

In [223]:
car_new

mpg  cylinders  displacement horsepower  weight  acceleration  \
0    18.0          8         307.0        130    3504          12.0   
1    15.0          8         350.0        165    3693          11.5   
2    18.0          8         318.0        150    3436          11.0   
3    16.0          8         304.0        150    3433          12.0   
4    17.0          8         302.0        140    3449          10.5   
..    ...        ...           ...        ...     ...           ...   
393  27.0          4         140.0         86    2790          15.6   
394  44.0          4          97.0         52    2130          24.6   
395  32.0          4         135.0         84    2295          11.6   
396  28.0          4         120.0         79    2625          18.6   
397  31.0          4         119.0         82    2720          19.4   

     model year  
0            70  
1            70  
2            70  
3            70  
4            70  
..          ...  
393          82  
394          82  
395          82  
396          82  
397          82  

[398 rows x 7 columns]